version: '3'
services:

#  datastore:
#    image: liccioni/seen-data-store:latest
#    ports:
#      - "9000:9000"
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_BROKER_HOST: "kafka:9092"
#      MONGODB_HOST: "mongo:27017"
#      MONGODB_PASSWORD: "spring"

  endpoint:
    image: esmartit/access-point-incoming-endpoint:2.1.0
    ports:
      - "9001:9000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_HOST: "kafka:9092"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "smartpoke-device-presence:1:1,smartpoke-registered-users:1:1,smartpoke-session-activity:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  mongo:
    image: mongo:4.4.1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password