spring.application.name: smartpoke-data-store
server.port: "${SERVER_PORT:9000}"
spring:
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER:spring}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:27017/smartpoke"
  cloud.stream:
    kafka:
      binder:
        brokers: "${KAFKA_BROKER_HOST}"
    bindings:
      input:
        destination: "smartpoke-device-presence"
        group: "smartpoke.sensor-activity.data-store.2"
      unique-devices-detected-count-input:
        destination: "smartpoke-unique-devices-detected-count"
        group: "smartpoke.sensor-activity.data-store.2"
      hourly-device-presence-count-input:
        destination: "smartpoke-hourly-presence-count"
        group: "smartpoke.sensor-activity.data-store.2"
      restream-output:
        destination: "smartpoke-device-presence"
      smartpoke-daily-unique-devices-detected-count-input:
        destination: "smartpoke-daily-unique-devices-detected-count"
        group: "smartpoke.sensor-activity.data-store.daily.unique.2"

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, prometheus