spring.application.name: smartpoke-data-store
server.port: "${SERVER_PORT:9000}"
spring:
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER:spring}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:27017/smartpoke"
  cloud.stream:
    kafka:
      binder:
        brokers: "${KAFKA_BROKER_HOST}"
    bindings:
      input:
        destination: "smartpoke-device-presence"
        group: "smartpoke.data-store.device-presence"
      unique-devices-detected-count-input:
        destination: "smartpoke-unique-devices-detected-count"
        group: "smartpoke.data-store.unique-devices-detected-count"
      hourly-device-presence-count-input:
        destination: "smartpoke-hourly-presence-count"
        group: "smartpoke.data-store.hourly-presence-count"
      restream-output:
        destination: "smartpoke-device-presence"
      smartpoke-daily-unique-devices-detected-count-input:
        destination: "smartpoke-daily-unique-devices-detected-count"
        group: "smartpoke.data-store.daily-unique-devices-detected-count"
      minute-device-presence-count-input:
        destination: "smartpoke-minute-presence-count"
        group: "smartpoke.data-store.minute-presence-count"
      device-position-input:
        destination: "smartpoke-device-position"
        group: "smartpoke.data-store.device-position"
      registered-device-input:
        destination: "smartpoke-registered-users"
        group: "smartpoke.data-store.registered-users"
      radius-activity-input:
        destination: "smartpoke-session-activity"
        group: "smartpoke.data-store.radius-activity"

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, prometheus