server.port: 9000
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
spring:
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER:spring}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:27017/smartpoke"
  cloud.stream:
    kafka:
      binder:
        brokers: "${KAFKA_BROKER_HOST}"
    bindings:
      input:
        destination: "${KAFKA_TOPIC}"
        group: "smartpoke.sensor-activity.data-store.4"