spring.application.name: smartpoke-data-store
server.port: "${SERVER_PORT:9000}"
spring:
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER:spring}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost:2017}/smartpoke"
  cloud:
    stream:
      kafka:
        binder:
          brokers: "${KAFKA_BROKER_HOST}"
          auto-add-partitions: false
          auto-create-topics: false
          consumer-properties:
            max.poll.records: 200
#            max.poll.interval.ms: 300000
#            auto.offset.reset: earliest
      bindings:
        input:
          destination: "smartpoke-device-presence"
          group: "smartpoke.data-store"
        registered-device-input:
          destination: "smartpoke-registered-users"
          group: "smartpoke.data-store"
        radius-activity-input:
          destination: "smartpoke-session-activity"
          group: "smartpoke.data-store"
        restream-output:
          destination: "smartpoke-device-presence"

management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics, health, prometheus