logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
spring:
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER:root}:${MONGODB_PASSWORD:example}@${MONGODB_HOST:localhost}:27017/smartpoke?authSource=admin&authMechanism=SCRAM-SHA-1"