server.port: 9000
spring:
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/smartpoke"
  cloud.stream:
    kafka:
      binder:
        brokers: "${KAFKA_BROKER_HOST}"
    bindings:
      input:
        destination: "${KAFKA_TOPIC}"
        group: "smartpoke.seen-devices.data-store"