server.port: "${SERVER_PORT:9000}"
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
spring:
  data:
    mongodb:
#      uri: "mongodb://${MONGODB_USER:spring}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:27017/smartPoke?authSource=admin&authMechanism=SCRAM-SHA-1"
      uri: "mongodb://${MONGODB_USER:spring}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:27017/smartpoke"
  cloud.stream:
    kafka:
      binder:
        brokers: "${KAFKA_BROKER_HOST}"
    bindings:
      input:
        destination: "smartpoke-device-presence"
        group: "smartpoke.sensor-activity.data-store"
      unique-devices-detected-count-input:
        destination: "unique-devices-detected-count"
        group: "smartpoke.sensor-activity.data-store"
      restream-output:
        destination: "smartpoke-device-presence"